//! Deployment resource policies shared across Ocelotl boundaries.
//!
//! The defaults are intentionally conservative alpha ceilings. Callers that
//! operate in a more constrained environment can supply lower limits through
//! the explicit `with_limits` entry points owned by runtime and loader crates.

use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::{InvalidModelError, InvalidRequestError, OcelotlError, Result};

/// Resource ceilings for one generation or transcription request.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct RequestLimits {
    /// Maximum caller-supplied prompt tokens.
    pub max_prompt_tokens: usize,
    /// Maximum tokens generated by one request.
    pub max_new_tokens: usize,
    /// Maximum prompt plus generated-token context.
    pub max_context_tokens: usize,
    /// Maximum 16 kHz mono samples accepted by one transcription request.
    pub max_audio_samples: usize,
}

impl Default for RequestLimits {
    fn default() -> Self {
        Self {
            max_prompt_tokens: 131_072,
            max_new_tokens: 4_096,
            max_context_tokens: 131_072,
            // One standard Whisper 30-second audio window at 16 kHz.
            max_audio_samples: 30 * 16_000,
        }
    }
}

impl RequestLimits {
    /// Validate that this policy is internally consistent.
    pub fn validate(&self) -> Result<()> {
        if self.max_prompt_tokens == 0
            || self.max_new_tokens == 0
            || self.max_context_tokens == 0
            || self.max_audio_samples == 0
        {
            return Err(invalid_request(
                "request_limits",
                "all request limits must be greater than zero",
            ));
        }
        if self.max_prompt_tokens > self.max_context_tokens {
            return Err(invalid_request(
                "request_limits.max_prompt_tokens",
                format!(
                    "max_prompt_tokens {} exceeds max_context_tokens {}",
                    self.max_prompt_tokens, self.max_context_tokens
                ),
            ));
        }
        if self.max_new_tokens > self.max_context_tokens {
            return Err(invalid_request(
                "request_limits.max_new_tokens",
                format!(
                    "max_new_tokens {} exceeds max_context_tokens {}",
                    self.max_new_tokens, self.max_context_tokens
                ),
            ));
        }
        Ok(())
    }

    /// Validate prompt/output limits and return their checked total context.
    pub fn validate_generation(
        &self,
        prompt_tokens: usize,
        max_new_tokens: usize,
    ) -> Result<usize> {
        self.validate()?;
        let context_tokens = prompt_tokens.checked_add(max_new_tokens).ok_or_else(|| {
            invalid_request(
                "context_tokens",
                "prompt_tokens + max_new_tokens overflows usize",
            )
        })?;

        if prompt_tokens > self.max_prompt_tokens {
            return Err(invalid_request(
                "prompt_tokens",
                format!(
                    "prompt token count {prompt_tokens} exceeds configured limit {}",
                    self.max_prompt_tokens
                ),
            ));
        }
        if max_new_tokens > self.max_new_tokens {
            return Err(invalid_request(
                "max_new_tokens",
                format!(
                    "requested {max_new_tokens} exceeds configured limit {}",
                    self.max_new_tokens
                ),
            ));
        }
        if context_tokens > self.max_context_tokens {
            return Err(invalid_request(
                "context_tokens",
                format!(
                    "prompt_tokens ({prompt_tokens}) + max_new_tokens ({max_new_tokens}) = {context_tokens} exceeds configured limit {}",
                    self.max_context_tokens
                ),
            ));
        }

        Ok(context_tokens)
    }

    /// Validate input audio size before preprocessing allocates or computes.
    pub fn validate_audio_samples(&self, audio_samples: usize) -> Result<()> {
        self.validate()?;
        if audio_samples > self.max_audio_samples {
            return Err(invalid_request(
                "audio_samples",
                format!(
                    "audio sample count {audio_samples} exceeds configured limit {}",
                    self.max_audio_samples
                ),
            ));
        }
        Ok(())
    }
}

/// Resource ceilings for local model artifacts and their bounded headers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArtifactLimits {
    pub max_file_bytes: u64,
    pub max_header_bytes: u64,
    pub max_metadata_entries: u64,
    pub max_tensors: u64,
    pub max_metadata_string_bytes: u64,
    pub max_key_bytes: u64,
    pub max_tensor_name_bytes: u64,
    pub max_array_elements: u64,
    pub max_array_depth: usize,
    pub max_tensor_dimensions: u32,
}

impl Default for ArtifactLimits {
    fn default() -> Self {
        Self {
            max_file_bytes: 32 * 1024 * 1024 * 1024,
            max_header_bytes: 512 * 1024 * 1024,
            max_metadata_entries: 65_536,
            max_tensors: 131_072,
            max_metadata_string_bytes: 16 * 1024 * 1024,
            max_key_bytes: 65_535,
            max_tensor_name_bytes: 65_535,
            // Gemma4's embedded tokenizer is roughly 262k entries.
            max_array_elements: 1_000_000,
            max_array_depth: 4,
            max_tensor_dimensions: 8,
        }
    }
}

impl ArtifactLimits {
    /// Validate that this policy is internally consistent.
    pub fn validate(&self) -> Result<()> {
        if self.max_file_bytes == 0
            || self.max_header_bytes == 0
            || self.max_metadata_entries == 0
            || self.max_tensors == 0
            || self.max_metadata_string_bytes == 0
            || self.max_key_bytes == 0
            || self.max_tensor_name_bytes == 0
            || self.max_array_elements == 0
            || self.max_array_depth == 0
            || self.max_tensor_dimensions == 0
        {
            return Err(invalid_request(
                "artifact_limits",
                "all artifact limits must be greater than zero",
            ));
        }
        if self.max_header_bytes > self.max_file_bytes {
            return Err(invalid_request(
                "artifact_limits.max_header_bytes",
                format!(
                    "max_header_bytes {} exceeds max_file_bytes {}",
                    self.max_header_bytes, self.max_file_bytes
                ),
            ));
        }
        if self.max_key_bytes > self.max_metadata_string_bytes
            || self.max_tensor_name_bytes > self.max_metadata_string_bytes
        {
            return Err(invalid_request(
                "artifact_limits.max_metadata_string_bytes",
                "metadata string limit must cover key and tensor-name limits",
            ));
        }
        Ok(())
    }

    pub fn validate_file_bytes(&self, path: Option<&Path>, file_bytes: u64) -> Result<()> {
        self.validate()?;
        if file_bytes > self.max_file_bytes {
            return Err(invalid_model(
                path,
                "file_size",
                format!(
                    "artifact file size {file_bytes} exceeds configured limit {}",
                    self.max_file_bytes
                ),
            ));
        }
        Ok(())
    }

    pub fn validate_gguf_counts(
        &self,
        path: Option<&Path>,
        tensor_count: u64,
        metadata_count: u64,
    ) -> Result<()> {
        self.validate()?;
        if tensor_count > self.max_tensors {
            return Err(invalid_model(
                path,
                "tensor_count",
                format!(
                    "GGUF tensor_count {tensor_count} exceeds configured limit {}",
                    self.max_tensors
                ),
            ));
        }
        if metadata_count > self.max_metadata_entries {
            return Err(invalid_model(
                path,
                "metadata_kv_count",
                format!(
                    "GGUF metadata_kv_count {metadata_count} exceeds configured limit {}",
                    self.max_metadata_entries
                ),
            ));
        }
        Ok(())
    }
}

fn invalid_request(field: impl Into<String>, message: impl Into<String>) -> OcelotlError {
    OcelotlError::InvalidRequest(InvalidRequestError {
        field: field.into(),
        message: message.into(),
    })
}

fn invalid_model(
    path: Option<&Path>,
    field: impl Into<String>,
    message: impl Into<String>,
) -> OcelotlError {
    OcelotlError::InvalidModel(InvalidModelError {
        path: path.map(Path::to_path_buf),
        field: Some(field.into()),
        message: message.into(),
    })
}
